Jb59383 devel
MeeGoIntegration/boss pull request #4
Opened 2022-11-24 10:46 UTC by lbt

Include the Sequel adaptor and support connection to a postgress DB
Improve config handling
Update gems

2022-11-29 20:57 UTC, keto requested changes

2022-11-29 20:57 UTC, keto commented on .gitmodules
> +[submodule "ruote-redis"]
The configuration does not support the redis storage, so I'm not sure if it makes sense to add the module yet.

2022-11-29 20:57 UTC, keto commented on Makefile
> -install: vendor/build
The point of having the install in the Makefile was to make local testing and development easier. I would keep it here unless it is causing some issues. I'm also not sure how moving it to spec makes things any simpler like the commit message suggests.

2022-11-29 20:57 UTC, keto commented on boss.conf
> +# if db is specified it takes priority
I think this might cause confusion. If both are defined it should probably throw an error.
Or there could be just one option db, which takes file:// or postgres:// url. Not sure if e really need to care about the backwards compatibility for old configs.

2022-11-29 20:57 UTC, keto commented on boss.conf
> -viewer_address = 127.0.0.1
I would keep the default as localhost only.

2022-11-29 20:57 UTC, keto commented on rpm/boss.spec
> +Version: 0.11.0+eos.20221111091745.7.gccc62f0
oops?

2022-12-07 14:06 UTC, lbt commented on Makefile
> -install: vendor/build
I fixed up the issue in osc by fixing the Makefile to not depend on the vendor/build dir instead

2022-12-14 13:32 UTC, keto approved these changes

2022-12-14 13:34 UTC, merged